using System.Xml;
using Whisper.net;

namespace Phonematic.Helpers;

/// <summary>
/// Legacy Whisper-based PhoScript writer, retained for the GUI's <c>"whisper"</c>
/// transcription backend. IPA symbols come from <see cref="CmuDict"/> /
/// <see cref="GraphemeToPhoneme"/> / <see cref="ArpabetToIpa"/>; prosodic measurement
/// fields are omitted and timing is approximated.
/// <para>
/// The acoustic pipeline uses <see cref="PhoScriptWriter.Write(System.Collections.Generic.IReadOnlyList{Phonematic.Models.PhoneAlignment}, System.Collections.Generic.IReadOnlyList{Phonematic.Models.AcousticFeatureFrame}, Phonematic.Models.SpeakerBaseline, string, string, System.DateOnly?)"/>
/// in the shared <c>Phonematic</c> project; prefer it when acoustic analysis results
/// are available.
/// </para>
/// <para>
/// All XML emission goes through <see cref="XmlWriter"/>, which handles attribute-value
/// escaping automatically.
/// </para>
/// </summary>
public static class PhoScriptWriterLegacy
{
    // Indent with two spaces, LF line endings, no XML declaration.
    private static readonly XmlWriterSettings XmlSettings = new()
    {
        Indent = true,
        IndentChars = "  ",
        NewLineChars = "\n",
        NewLineOnAttributes = false,
        ConformanceLevel = ConformanceLevel.Fragment,
        OmitXmlDeclaration = true,
        CloseOutput = false,
    };

    /// <summary>
    /// Builds a PhoScript document from Whisper segment data.
    /// IPA symbols come from <see cref="CmuDict"/> / <see cref="GraphemeToPhoneme"/>;
    /// prosodic measurement fields are omitted and timing is approximated.
    /// </summary>
    public static string WriteLegacy(
        IReadOnlyList<SegmentData> segments,
        string sourceFileName,
        DateOnly? recordedDate = null)
    {
        var date = recordedDate ?? DateOnly.FromDateTime(DateTime.UtcNow);
        var recordingId = Path.GetFileNameWithoutExtension(sourceFileName);

        using var sw = new StringWriter();

        // PhoScript header comments — plain text, written before the XML body.
        sw.WriteLine("## PhoScript 1.0 — generated by Phonematic (Whisper legacy)");
        sw.WriteLine($"## source: {sourceFileName}");
        sw.WriteLine($"## generated: {DateTime.UtcNow:yyyy-MM-ddTHH:mm:ssZ}");
        sw.WriteLine();

        using (var xw = XmlWriter.Create(sw, XmlSettings))
        {
            for (var i = 0; i < segments.Count; i++)
            {
                var seg = segments[i];
                var durationMs = (int)(seg.End - seg.Start).TotalMilliseconds;
                var lang = string.IsNullOrWhiteSpace(seg.Language) ? "und" : seg.Language;
                var segStartMs = (int)seg.Start.TotalMilliseconds;

                xw.WriteStartElement("sentence");
                xw.WriteAttributeString("id", $"utt_{i + 1:D3}");
                xw.WriteAttributeString("lang", lang);
                xw.WriteAttributeString("duration_ms", durationMs.ToString());

                xw.WriteStartElement("meta");
                xw.WriteAttributeString("recording_id", recordingId);
                xw.WriteAttributeString("date", date.ToString("yyyy-MM-dd"));
                xw.WriteAttributeString("asr_model", "whisper");
                xw.WriteAttributeString("asr_confidence", seg.Probability.ToString("F4"));
                xw.WriteEndElement(); // </meta>

                var words = SplitWords(seg.Text.Trim());
                var msPerWord = durationMs / Math.Max(words.Count, 1);

                for (var w = 0; w < words.Count; w++)
                {
                    var wordStart = segStartMs + w * msPerWord;
                    var wordEnd = w < words.Count - 1
                        ? segStartMs + (w + 1) * msPerWord
                        : segStartMs + durationMs;
                    var boundary = w == words.Count - 1 ? "IP_end" : "none";
                    var wordDurMs = wordEnd - wordStart;
                    var ipaPhones = GetIpaPhones(words[w]);
                    var msPerPhone = ipaPhones.Count > 0 ? wordDurMs / ipaPhones.Count : 0;

                    xw.WriteStartElement("word");
                    xw.WriteAttributeString("orth", words[w]);
                    xw.WriteAttributeString("t_start", wordStart.ToString());
                    xw.WriteAttributeString("t_end", wordEnd.ToString());
                    xw.WriteAttributeString("phrase_boundary", boundary);

                    for (var p = 0; p < ipaPhones.Count; p++)
                    {
                        var phoneStart = wordStart + p * msPerPhone;
                        var phoneEnd = p < ipaPhones.Count - 1
                            ? wordStart + (p + 1) * msPerPhone
                            : wordEnd;

                        xw.WriteStartElement("phon");
                        xw.WriteAttributeString("ipa", ipaPhones[p]);
                        xw.WriteAttributeString("t_start", phoneStart.ToString());
                        xw.WriteAttributeString("t_end", phoneEnd.ToString());
                        xw.WriteAttributeString("dur_ms", (phoneEnd - phoneStart).ToString());
                        xw.WriteEndElement(); // </phon>
                    }

                    xw.WriteEndElement(); // </word>
                }

                xw.WriteEndElement(); // </sentence>
            }
        }

        sw.WriteLine();
        return sw.ToString().Replace("\r\n", "\n");
    }

    /// <summary>
    /// Returns the IPA phones for a single orthographic word as slash-delimited IPA
    /// strings. Looks up the CMU Pronouncing Dictionary first; falls back to
    /// rule-based G2P for unknown words.
    /// </summary>
    internal static List<string> GetIpaPhones(string word)
    {
        string[] arpabet;
        if (!CmuDict.TryGetPhones(word, out arpabet!))
            arpabet = GraphemeToPhoneme.Convert(word);

        var phones = new List<string>();
        foreach (var symbol in arpabet)
            foreach (var part in symbol.Split(' ', StringSplitOptions.RemoveEmptyEntries))
                phones.Add(ArpabetToIpa.Convert(part));

        return phones;
    }

    /// <summary>Splits <paramref name="text"/> on whitespace, discarding empty entries.</summary>
    internal static List<string> SplitWords(string text) =>
        text.Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .ToList();

    /// <summary>
    /// Escapes the minimal set of XML attribute characters.
    /// <para>
    /// This helper is retained for use in tests and any code that constructs raw XML
    /// strings outside of <see cref="XmlWriter"/>. All internal XML emission now goes
    /// through <see cref="XmlWriter"/>, which handles escaping automatically.
    /// </para>
    /// </summary>
    internal static string Escape(string value) =>
        value.Replace("&", "&amp;").Replace("\"", "&quot;").Replace("<", "&lt;").Replace(">", "&gt;");
}
