using System.Text;
using Whisper.net;

namespace Phonematic.Helpers;

/// <summary>
/// Serializes a collection of Whisper <see cref="SegmentData"/> results to
/// <see href="https://github.com/davidpizon/Phonematic/blob/main/docs/PHOSCRIPT.md">PhoScript 1.0</see>
/// format (<c>.phos</c>).
/// <para>
/// Because Whisper provides segment-level timestamps and word text but no sub-phoneme
/// acoustic measurements, all prosodic fields that require forced-alignment or signal
/// analysis are omitted. Word-level timing is approximated by distributing each
/// segment's duration uniformly across its constituent words. ASR confidence scores
/// from Whisper tokens are recorded using the reserved <c>asr_*</c> extension
/// namespace defined by the spec.
/// </para>
/// </summary>
public static class PhoScriptWriter
{
    /// <summary>
    /// Builds a PhoScript document from the given segments and source file metadata.
    /// </summary>
    /// <param name="segments">Ordered list of Whisper segments.</param>
    /// <param name="sourceFileName">Base name of the original audio file (used in <c>&lt;meta&gt;</c>).</param>
    /// <param name="recordedDate">
    /// Date to embed in the <c>&lt;meta&gt;</c> block. Defaults to today when <see langword="null"/>.
    /// </param>
    /// <returns>UTF-8 PhoScript document as a string (LF line endings, no BOM).</returns>
    public static string Write(
        IReadOnlyList<SegmentData> segments,
        string sourceFileName,
        DateOnly? recordedDate = null)
    {
        var date = recordedDate ?? DateOnly.FromDateTime(DateTime.UtcNow);
        var sb = new StringBuilder();

        sb.AppendLine("## PhoScript 1.0 — generated by Phonematic");
        sb.AppendLine($"## source: {sourceFileName}");
        sb.AppendLine($"## generated: {DateTime.UtcNow:yyyy-MM-ddTHH:mm:ssZ}");
        sb.AppendLine();

        for (var i = 0; i < segments.Count; i++)
        {
            var seg = segments[i];
            var sentenceId = $"utt_{i + 1:D3}";
            var durationMs = (int)(seg.End - seg.Start).TotalMilliseconds;
            var lang = string.IsNullOrWhiteSpace(seg.Language) ? "und" : seg.Language;

            sb.AppendLine($"<sentence id=\"{sentenceId}\" lang=\"{lang}\" duration_ms=\"{durationMs}\">");
            sb.AppendLine($"  <meta recording_id=\"{Path.GetFileNameWithoutExtension(sourceFileName)}\"");
            sb.AppendLine($"        date=\"{date:yyyy-MM-dd}\"");
            sb.AppendLine($"        asr_model=\"whisper\" asr_confidence=\"{seg.Probability:F4}\"/>");
            sb.AppendLine();

            var words = SplitWords(seg.Text.Trim());
            if (words.Count > 0)
            {
                var segStartMs = (int)seg.Start.TotalMilliseconds;
                var msPerWord = words.Count > 0 ? durationMs / words.Count : 0;

                for (var w = 0; w < words.Count; w++)
                {
                    var wordStart = segStartMs + w * msPerWord;
                    var wordEnd = w < words.Count - 1
                        ? segStartMs + (w + 1) * msPerWord
                        : segStartMs + durationMs;
                    var isLast = w == words.Count - 1;
                    var boundary = isLast ? "IP_end" : "none";

                    sb.AppendLine($"  <word orth=\"{Escape(words[w])}\"");
                    sb.AppendLine($"        t_start=\"{wordStart}\" t_end=\"{wordEnd}\"");
                    sb.AppendLine($"        phrase_boundary=\"{boundary}\"/>");
                }
            }

            sb.AppendLine();
            sb.AppendLine("</sentence>");
            sb.AppendLine();
        }

        // Normalise to LF as required by the spec
        return sb.ToString().Replace("\r\n", "\n");
    }

    /// <summary>Splits <paramref name="text"/> on whitespace, discarding empty entries.</summary>
    internal static List<string> SplitWords(string text) =>
        text.Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .ToList();

    /// <summary>Escapes the minimal set of XML attribute characters.</summary>
    internal static string Escape(string value) =>
        value.Replace("&", "&amp;").Replace("\"", "&quot;").Replace("<", "&lt;").Replace(">", "&gt;");
}
