// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Phonematic.Data;

#nullable disable

namespace Phonematic.Migrations
{
    [DbContext(typeof(PhonematicDbContext))]
    partial class PhonematicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Phonematic.Models.PlaudRecording", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DownloadedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaudFileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaudFileId")
                        .IsUnique();

                    b.ToTable("PlaudRecordings");
                });

            modelBuilder.Entity("Phonematic.Models.ProcessedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AudioDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TranscribedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("TranscriptionDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("TranscriptionPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WhisperModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilePath");

                    b.HasIndex("FilePath", "FileHash")
                        .IsUnique();

                    b.ToTable("ProcessedFiles");
                });

            modelBuilder.Entity("Phonematic.Models.TranscriptionChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("ProcessedFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedFileId");

                    b.ToTable("TranscriptionChunks");
                });

            modelBuilder.Entity("Phonematic.Models.TranscriptionChunk", b =>
                {
                    b.HasOne("Phonematic.Models.ProcessedFile", "ProcessedFile")
                        .WithMany("Chunks")
                        .HasForeignKey("ProcessedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessedFile");
                });

            modelBuilder.Entity("Phonematic.Models.ProcessedFile", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
