// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transcriptonator.Data;

#nullable disable

namespace Transcriptonator.Migrations
{
    [DbContext(typeof(TranscriptonatorDbContext))]
    partial class TranscriptonatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Transcriptonator.Models.ProcessedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AudioDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TranscribedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("TranscriptionDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("TranscriptionPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WhisperModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilePath");

                    b.HasIndex("FilePath", "FileHash")
                        .IsUnique();

                    b.ToTable("ProcessedFiles");
                });

            modelBuilder.Entity("Transcriptonator.Models.TranscriptionChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("ProcessedFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedFileId");

                    b.ToTable("TranscriptionChunks");
                });

            modelBuilder.Entity("Transcriptonator.Models.TranscriptionChunk", b =>
                {
                    b.HasOne("Transcriptonator.Models.ProcessedFile", "ProcessedFile")
                        .WithMany("Chunks")
                        .HasForeignKey("ProcessedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessedFile");
                });

            modelBuilder.Entity("Transcriptonator.Models.ProcessedFile", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
